import Foundation
import SwiftUI

@MainActor
final class AppSettings: ObservableObject {
    enum KeepHistory: String, CaseIterable, Identifiable {
        case oneDay
        case oneWeek
        case oneMonth
        case forever

        var id: String { rawValue }

        var title: String {
            switch self {
            case .oneDay: return "1 Day"
            case .oneWeek: return "1 Week"
            case .oneMonth: return "1 Month"
            case .forever: return "Forever"
            }
        }

        var cutoffDate: Date? {
            let calendar = Calendar.current
            switch self {
            case .oneDay: return calendar.date(byAdding: .day, value: -1, to: Date())
            case .oneWeek: return calendar.date(byAdding: .day, value: -7, to: Date())
            case .oneMonth: return calendar.date(byAdding: .month, value: -1, to: Date())
            case .forever: return nil
            }
        }
    }

    @AppStorage("clipboardCheckInterval") var clipboardCheckInterval: Double = 0.35
    @AppStorage("capturePaused") var capturePaused: Bool = false
    @AppStorage("keepHistory") private var keepHistoryRaw: String = KeepHistory.forever.rawValue
    @AppStorage("maxHistoryItems") var maxHistoryItems: Int = 5000
    @AppStorage("maxBlobMegabytes") var maxBlobMegabytes: Int = 1024
    @AppStorage("launchAtLogin") var launchAtLogin: Bool = true
    @AppStorage("pasteAsPlainTextByDefault") var pasteAsPlainTextByDefault: Bool = false
    @AppStorage("pasteStackDefaultDirection") private var pasteStackDefaultDirectionRaw: String =
        PasteStackController.Direction.oldestFirst.rawValue
    @AppStorage("ignoredBundleIdentifiers") private var ignoredBundleIdentifiersRaw: String = defaultIgnoredApps.joined(separator: "\n")
    @AppStorage("ignoredPasteboardTypes") private var ignoredPasteboardTypesRaw: String = defaultIgnoredTypes.joined(separator: "\n")

    var keepHistory: KeepHistory {
        get { KeepHistory(rawValue: keepHistoryRaw) ?? .forever }
        set { keepHistoryRaw = newValue.rawValue }
    }

    var pasteStackDefaultDirection: PasteStackController.Direction {
        get {
            PasteStackController.Direction(rawValue: pasteStackDefaultDirectionRaw) ?? .oldestFirst
        }
        set {
            pasteStackDefaultDirectionRaw = newValue.rawValue
            objectWillChange.send()
        }
    }

    var ignoredBundleIdentifiers: Set<String> {
        get { Set(Self.lines(from: ignoredBundleIdentifiersRaw)) }
        set {
            ignoredBundleIdentifiersRaw = newValue.sorted().joined(separator: "\n")
            objectWillChange.send()
        }
    }

    var ignoredBundleIdentifiersText: String {
        get { ignoredBundleIdentifiersRaw }
        set { ignoredBundleIdentifiersRaw = newValue }
    }

    var ignoredPasteboardTypes: Set<String> {
        get { Set(Self.lines(from: ignoredPasteboardTypesRaw)) }
        set { ignoredPasteboardTypesRaw = newValue.sorted().joined(separator: "\n") }
    }

    var ignoredPasteboardTypesText: String {
        get { ignoredPasteboardTypesRaw }
        set { ignoredPasteboardTypesRaw = newValue }
    }

    func isIgnored(bundleIdentifier: String?) -> Bool {
        guard let bundleIdentifier else { return false }
        return ignoredBundleIdentifiers.contains(bundleIdentifier)
    }

    func ignoresPasteboardType(_ rawType: String) -> Bool {
        ignoredPasteboardTypes.contains(rawType)
    }

    private static func lines(from value: String) -> [String] {
        value
            .split(whereSeparator: \.isNewline)
            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
            .filter { !$0.isEmpty }
    }
}

private let defaultIgnoredApps = [
    "com.agilebits.onepassword7",
    "com.1password.1password",
    "com.lastpass.LastPass",
    "com.bitwarden.desktop",
    "com.apple.keychainaccess"
]

private let defaultIgnoredTypes = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
    "com.agilebits.onepassword",
    "com.typeit4me.clipping",
    "de.petermaurer.TransientPasteboardType",
    "net.antelle.keeweb",
    "Pasteboard generator type"
]
