"""Traditional Chinese and Korean translations."""

from __future__ import annotations

BATCH_CJK_LANGS = ("zh-Hant", "ko")

BATCH_CJK: dict[str, dict[str, str]] = {
    "filter.all": {"zh-Hant": "所有類型", "ko": "모든 유형"},
    "filter.text": {"zh-Hant": "文字", "ko": "텍스트"},
    "filter.number": {"zh-Hant": "數字", "ko": "숫자"},
    "filter.link": {"zh-Hant": "連結", "ko": "링크"},
    "filter.image": {"zh-Hant": "圖片", "ko": "이미지"},
    "filter.file": {"zh-Hant": "檔案", "ko": "파일"},
    "filter.byType": {"zh-Hant": "依類型篩選", "ko": "유형별 필터"},
    "filter.clear": {"zh-Hant": "清除類型篩選", "ko": "유형 필터 지우기"},
    "tab.default": {"zh-Hant": "預設", "ko": "기본"},
    "tab.pinned": {"zh-Hant": "已釘選", "ko": "고정됨"},
    "tab.folder": {"zh-Hant": "檔案夾", "ko": "폴더"},
    "clipType.text": {"zh-Hant": "文字", "ko": "텍스트"},
    "clipType.richText": {"zh-Hant": "富文字", "ko": "서식 있는 텍스트"},
    "clipType.html": {"zh-Hant": "HTML", "ko": "HTML"},
    "clipType.image": {"zh-Hant": "圖片", "ko": "이미지"},
    "clipType.file": {"zh-Hant": "檔案", "ko": "파일"},
    "clipType.url": {"zh-Hant": "連結", "ko": "링크"},
    "clipType.mixed": {"zh-Hant": "混合", "ko": "혼합"},
    "clipType.folder": {"zh-Hant": "檔案夾", "ko": "폴더"},
    "clipType.empty": {"zh-Hant": "空白", "ko": "비어 있음"},
    "clipPreview.oneCharacter": {"zh-Hant": "1 個字元", "ko": "글자 1개"},
    "clipPreview.characters": {"zh-Hant": "%lld 個字元", "ko": "글자 %lld개"},
    "keepHistory.oneDay": {"zh-Hant": "1 天", "ko": "1일"},
    "keepHistory.oneWeek": {"zh-Hant": "1 週", "ko": "1주"},
    "keepHistory.oneMonth": {"zh-Hant": "1 個月", "ko": "1개월"},
    "keepHistory.forever": {"zh-Hant": "永久", "ko": "영구"},
    "stack.fifo": {"zh-Hant": "先進先出", "ko": "선입선출"},
    "stack.lifo": {"zh-Hant": "後進先出", "ko": "후입선출"},
    "stack.fifoHelp": {
        "zh-Hant": "依複製順序。點一下以反轉。",
        "ko": "복사한 순서입니다. 클릭하여 순서를 바꿉니다.",
    },
    "stack.lifoHelp": {
        "zh-Hant": "最新的優先。點一下改為複製順序。",
        "ko": "최신 항목이 먼저입니다. 클릭하여 복사 순서로 바꿉니다.",
    },
    "stack.paste": {"zh-Hant": "貼上", "ko": "붙여넣기"},
    "stack.open": {"zh-Hant": "打開貼上堆疊", "ko": "붙여넣기 스택 열기"},
    "stack.close": {"zh-Hant": "關閉貼上堆疊", "ko": "붙여넣기 스택 닫기"},
    "stack.title": {"zh-Hant": "堆疊", "ko": "스택"},
    "stack.statusWithCount": {"zh-Hant": "堆疊 · %lld", "ko": "스택 · %lld"},
    "stack.collecting": {"zh-Hant": "收集中", "ko": "수집 중"},
    "stack.closeHelp": {"zh-Hant": "關閉貼上堆疊 (⇧⌘C)", "ko": "붙여넣기 스택 닫기(⇧⌘C)"},
    "stack.pasteNext": {"zh-Hant": "⌘V 貼上下一項", "ko": "⌘V로 다음 항목 붙여넣기"},
    "stack.emptyTitle": {"zh-Hant": "複製內容以填入堆疊", "ko": "복사하여 스택을 채우세요"},
    "stack.emptySubtitle": {"zh-Hant": "然後在任意 App 中按 ⌘V", "ko": "이후 원하는 App에서 ⌘V"},
    "stack.accessibilityHint": {
        "zh-Hant": "請允許「輔助使用」，⌘V 才能推進堆疊",
        "ko": "⌘V로 스택을 진행하려면 손쉬운 사용을 허용하세요",
    },
    "stack.resizeHelp": {"zh-Hant": "拖曳以調整高度", "ko": "드래그하여 높이 조절"},
    "stack.moveToNext": {"zh-Hant": "移到下一項", "ko": "다음으로 이동"},
    "stack.delete": {"zh-Hant": "刪除", "ko": "삭제"},
    "menu.openPaste": {"zh-Hant": "打開剪貼簿", "ko": "클립보드 열기"},
    "menu.clearStack": {"zh-Hant": "清空貼上堆疊", "ko": "붙여넣기 스택 비우기"},
    "menu.pastePlain": {"zh-Hant": "以純文字貼上", "ko": "서식 없이 붙여넣기"},
    "menu.pauseCapture": {"zh-Hant": "暫停擷取", "ko": "캡처 일시 정지"},
    "menu.resumeCapture": {"zh-Hant": "恢復擷取", "ko": "캡처 재개"},
    "menu.mcp": {"zh-Hant": "MCP", "ko": "MCP"},
    "menu.copyMcpURL": {"zh-Hant": "複製 MCP 網址", "ko": "MCP URL 복사"},
    "menu.preferences": {"zh-Hant": "設定…", "ko": "환경설정…"},
    "menu.checkUpdates": {"zh-Hant": "檢查更新項目…", "ko": "업데이트 확인…"},
    "menu.quit": {"zh-Hant": "結束 Paste It", "ko": "Paste It 종료"},
    "menu.more": {"zh-Hant": "更多", "ko": "더 보기"},
    "menu.statusTooltip": {
        "zh-Hant": "Paste It — 按住 ⌘C / ⌘V 可預覽按鍵",
        "ko": "Paste It — ⌘C / ⌘V를 누르고 있으면 키가 표시됩니다",
    },
    "menu.statusClickHint": {
        "zh-Hant": "左鍵：時間軸 · 右鍵：選單",
        "ko": "왼쪽 클릭: 타임라인 · 오른쪽 클릭: 메뉴",
    },
    "timeline.clearFilter": {"zh-Hant": "清除篩選", "ko": "필터 지우기"},
    "timeline.selectedCount": {
        "zh-Hant": "已選取 %lld 項 — 按 Return 貼上",
        "ko": "%lld개 선택됨 — Return으로 붙여넣기",
    },
    "timeline.newFolder": {"zh-Hant": "新增檔案夾", "ko": "새 폴더"},
    "timeline.newFolderHelp": {"zh-Hant": "新增檔案夾", "ko": "새 폴더"},
    "timeline.search": {"zh-Hant": "搜尋 (⌘F)", "ko": "검색(⌘F)"},
    "timeline.searchHistory": {"zh-Hant": "搜尋歷史記錄", "ko": "기록 검색"},
    "timeline.noMatch": {"zh-Hant": "沒有符合的項目", "ko": "일치하는 항목 없음"},
    "timeline.noTypeInPinned": {
        "zh-Hant": "「已釘選」中沒有 %@ 類型的項目",
        "ko": "고정됨에 %@ 항목이 없습니다",
    },
    "timeline.noTypeInFolder": {
        "zh-Hant": "此檔案夾中沒有 %@ 類型的項目",
        "ko": "이 폴더에 %@ 항목이 없습니다",
    },
    "timeline.noType": {
        "zh-Hant": "沒有 %@ 類型的項目",
        "ko": "%@ 항목이 없습니다",
    },
    "timeline.emptyDefault": {
        "zh-Hant": "複製一些內容以建立剪貼簿歷史記錄",
        "ko": "무엇이든 복사하여 클립보드 기록을 쌓아 보세요",
    },
    "timeline.emptyPinned": {
        "zh-Hant": "釘選項目以永久保留在此",
        "ko": "항목을 고정하면 여기에 계속 남습니다",
    },
    "timeline.emptyFolder": {
        "zh-Hant": "從快捷選單將項目加入此檔案夾",
        "ko": "우클릭 메뉴에서 이 폴더에 항목을 추가하세요",
    },
    "timeline.unpin": {"zh-Hant": "取消釘選", "ko": "고정 해제"},
    "timeline.pin": {"zh-Hant": "釘選", "ko": "고정"},
    "timeline.addToFolder": {"zh-Hant": "加入檔案夾", "ko": "폴더에 추가"},
    "timeline.removeFromFolder": {"zh-Hant": "從檔案夾移除", "ko": "폴더에서 제거"},
    "timeline.delete": {"zh-Hant": "刪除", "ko": "삭제"},
    "timeline.removeFromFolderAction": {"zh-Hant": "從檔案夾移除", "ko": "폴더에서 제거"},
    "timeline.copy": {"zh-Hant": "複製到剪貼簿", "ko": "클립보드에 복사"},
    "timeline.copyPlain": {"zh-Hant": "以純文字複製", "ko": "일반 텍스트로 복사"},
    "timeline.edit": {"zh-Hant": "編輯", "ko": "편집"},
    "timeline.cancel": {"zh-Hant": "取消", "ko": "취소"},
    "timeline.create": {"zh-Hant": "建立", "ko": "만들기"},
    "settings.tab.about": {"zh-Hant": "關於", "ko": "정보"},
    "settings.tab.general": {"zh-Hant": "一般", "ko": "일반"},
    "settings.tab.privacy": {"zh-Hant": "隱私權", "ko": "개인정보 보호"},
    "settings.tab.folders": {"zh-Hant": "檔案夾", "ko": "폴더"},
    "settings.tab.stack": {"zh-Hant": "貼上堆疊", "ko": "붙여넣기 스택"},
    "settings.tab.storage": {"zh-Hant": "儲存空間", "ko": "저장 공간"},
    "settings.version": {"zh-Hant": "Paste It %@ (%@)", "ko": "Paste It %@ (%@)"},
    "settings.aboutBlurb": {
        "zh-Hant": "Paste It 是本地優先的剪貼簿管理工具，歷史記錄僅保存在這台 Mac。",
        "ko": "Paste It은 로컬 우선 클립보드 관리 앱입니다. 기록은 이 Mac에만 저장됩니다.",
    },
    "settings.versionLabel": {"zh-Hant": "版本", "ko": "버전"},
    "settings.showTutorial": {"zh-Hant": "顯示教學課程…", "ko": "튜토리얼 보기…"},
    "settings.whatsNew": {"zh-Hant": "新功能…", "ko": "새로운 기능…"},
    "settings.checkingUpdates": {"zh-Hant": "正在檢查更新項目…", "ko": "업데이트 확인 중…"},
    "settings.pauseCapture": {"zh-Hant": "暫停剪貼簿擷取", "ko": "클립보드 캡처 일시 정지"},
    "settings.pastePlainDefault": {
        "zh-Hant": "預設以純文字貼上",
        "ko": "기본적으로 일반 텍스트로 붙여넣기",
    },
    "settings.plainTextFootnote": {
        "zh-Hant": "⌃⌘V 會貼上一次純文字，然後還原原本的剪貼簿內容（自動貼上需要「輔助使用」）。在時間軸中，⇧↩ 會以純文字貼上選取項目。",
        "ko": "⌃⌘V는 한 번 일반 텍스트로 붙여넣은 뒤 원래 클립보드를 복원합니다(자동 붙여넣기에는 손쉬운 사용이 필요합니다). 타임라인에서는 ⇧↩로 선택 항목을 일반 텍스트로 붙여넣습니다.",
    },
    "settings.launchAtLogin": {"zh-Hant": "登入時打開", "ko": "로그인 시 실행"},
    "settings.keepHistory": {"zh-Hant": "保留歷史記錄", "ko": "기록 보관"},
    "settings.maxHistoryItems": {"zh-Hant": "歷史記錄上限", "ko": "최대 기록 항목 수"},
    "settings.clipboardPolling": {"zh-Hant": "剪貼簿輪詢", "ko": "클립보드 확인 간격"},
    "settings.seconds": {"zh-Hant": "秒", "ko": "초"},
    "settings.stackDirection": {"zh-Hant": "預設貼上方向", "ko": "기본 붙여넣기 순서"},
    "settings.stackFootnote": {
        "zh-Hant": "⇧⌘C 可打開或關閉貼上堆疊。堆疊中有內容時，在任意 App 中按 ⌘V 會貼上下一項（需要「輔助使用」）。執行時控制項位於堆疊面板與 ⋯ 選單。",
        "ko": "⇧⌘C로 붙여넣기 스택을 열고 닫을 수 있습니다. 스택에 항목이 있는 동안 다른 App에서 ⌘V를 누르면 다음 항목이 붙여넣어집니다(손쉬운 사용 필요). 실행 중 제어는 스택 패널과 ⋯ 메뉴에 있습니다.",
    },
    "settings.maxBinaryStorage": {
        "zh-Hant": "二進位資料上限：%lld MB",
        "ko": "최대 바이너리 저장 용량: %lldMB",
    },
    "settings.pruneNow": {"zh-Hant": "立即整理", "ko": "지금 정리"},
    "settings.clearKeepPinned": {
        "zh-Hant": "清除歷史記錄，保留已釘選項目",
        "ko": "기록 지우기(고정 항목 유지)",
    },
    "settings.clearAllHistory": {"zh-Hant": "清除所有歷史記錄", "ko": "모든 기록 지우기"},
    "folders.pinnedFooter": {
        "zh-Hant": "「已釘選」標籤無法重新命名或刪除。請在項目上使用「釘選／取消釘選」來管理內容。",
        "ko": "고정됨 탭은 이름을 바꾸거나 삭제할 수 없습니다. 항목의 고정/고정 해제로 내용을 관리하세요.",
    },
    "folders.noCustom": {"zh-Hant": "沒有自訂檔案夾", "ko": "사용자 폴더 없음"},
    "folders.rename": {"zh-Hant": "重新命名…", "ko": "이름 변경…"},
    "folders.addHelp": {"zh-Hant": "新增檔案夾", "ko": "폴더 추가"},
    "folders.renameHelp": {"zh-Hant": "重新命名檔案夾", "ko": "폴더 이름 변경"},
    "folders.deleteHelp": {"zh-Hant": "刪除檔案夾", "ko": "폴더 삭제"},
    "folders.footer": {
        "zh-Hant": "最多可建立 %lld 個自訂檔案夾，會顯示在「預設」與「已釘選」旁邊的標籤中。整理歷史記錄時，檔案夾中的項目會保留。",
        "ko": "사용자 폴더는 최대 %lld개까지 만들 수 있으며 기본 및 고정됨 옆 탭에 표시됩니다. 기록을 정리해도 폴더 안 항목은 유지됩니다.",
    },
    "folders.renameTitle": {"zh-Hant": "重新命名檔案夾", "ko": "폴더 이름 변경"},
    "folders.namePlaceholder": {"zh-Hant": "檔案夾名稱", "ko": "폴더 이름"},
    "folders.renameConfirm": {"zh-Hant": "重新命名", "ko": "이름 변경"},
    "privacy.analytics": {"zh-Hant": "分析", "ko": "분석"},
    "privacy.shareAnalytics": {
        "zh-Hant": "分享匿名使用分析資料",
        "ko": "익명 사용 분석 공유",
    },
    "privacy.whatWeCollect": {"zh-Hant": "我們收集的資料", "ko": "수집하는 데이터"},
    "privacy.eventsBlurb": {
        "zh-Hant": "事件資料有助於改進 Paste It（啟用、面板使用、更新等）。啟用後會以匿名方式傳送至 PostHog。",
        "ko": "이벤트는 Paste It 개선(활성화, 패널 사용, 업데이트 등)에 도움이 됩니다. 켜면 익명으로 PostHog에 전송됩니다.",
    },
    "privacy.neverCollected": {"zh-Hant": "絕不收集", "ko": "수집하지 않는 항목"},
    "privacy.productEvents": {"zh-Hant": "產品事件", "ko": "제품 이벤트"},
    "privacy.fullDisclosure": {"zh-Hant": "GitHub 上的完整說明", "ko": "GitHub에서 전체 공개 내용 보기"},
    "privacy.analyticsFooter": {
        "zh-Hant": "可選。關閉後不會傳送任何事件。詳見開放原始碼存放庫中的 %@。",
        "ko": "선택 사항입니다. 끄면 이벤트가 전송되지 않습니다. 오픈 소스 저장소의 %@를 참고하세요.",
    },
    "privacy.noIgnoredApps": {"zh-Hant": "沒有忽略的 App", "ko": "무시하는 App 없음"},
    "privacy.addApp": {"zh-Hant": "加入 App", "ko": "App 추가"},
    "privacy.removeApp": {"zh-Hant": "移除 App", "ko": "App 제거"},
    "privacy.ignoredApps": {"zh-Hant": "忽略的 App", "ko": "무시하는 App"},
    "privacy.ignoredAppsFooter": {
        "zh-Hant": "這些 App 中的複製內容不會存入歷史記錄。適用於密碼管理工具等敏感 App。",
        "ko": "이 App에서 복사한 내용은 기록에 저장되지 않습니다. 비밀번호 관리자 등 민감한 App에 사용하세요.",
    },
    "privacy.protectedContent": {"zh-Hant": "受保護內容", "ko": "보호된 콘텐츠"},
    "privacy.protectedBlurb": {
        "zh-Hant": "來自 App 的敏感剪貼簿標記（例如密碼欄位、暫時剪貼內容）會自動忽略。",
        "ko": "비밀번호 필드나 임시 클립처럼 App이 표시한 민감한 클립보드 데이터는 자동으로 무시됩니다.",
    },
    "privacy.protectedFooter": {
        "zh-Hant": "「忽略的 App」會略過整個 App 的所有內容；「受保護內容」只略過任何 App 中標記為敏感的剪貼簿資料。",
        "ko": "무시하는 App은 해당 App의 모든 복사를 건너뜁니다. 보호된 콘텐츠는 어떤 App이든 민감하다고 표시된 클립보드 데이터만 건너뜁니다.",
    },
    "privacy.addIgnoredApp": {"zh-Hant": "加入要忽略的 App", "ko": "무시할 App 추가"},
    "privacy.chooseApp": {"zh-Hant": "選擇…", "ko": "선택…"},
    "privacy.search": {"zh-Hant": "搜尋", "ko": "검색"},
    "privacy.loadingApps": {"zh-Hant": "正在載入 App…", "ko": "App 불러오는 중…"},
    "privacy.chooseAppPanel": {"zh-Hant": "選擇要忽略的 App", "ko": "무시할 App 선택"},
    "onboarding.capture.title": {"zh-Hant": "複製即可保存", "ko": "복사하여 저장"},
    "onboarding.paste.title": {"zh-Hant": "從時間軸選取", "ko": "타임라인에서 고르기"},
    "onboarding.browse.title": {"zh-Hant": "預覽與編輯", "ko": "미리보기 및 편집"},
    "onboarding.organize.title": {"zh-Hant": "多選貼上", "ko": "여러 항목 붙여넣기"},
    "onboarding.stack.title": {"zh-Hant": "貼上堆疊", "ko": "붙여넣기 스택"},
    "onboarding.capture.caption": {
        "zh-Hant": "複製任何內容 — Paste It 會保存，並在選單列閃爍 ⌘C。",
        "ko": "무엇이든 복사하세요. Paste It이 저장하고 메뉴 막대에서 ⌘C를 깜빡입니다.",
    },
    "onboarding.paste.caption": {
        "zh-Hant": "⇧⌘V 打開歷史記錄。在項目上按兩下，再按 ⌘V — 或按 ⌃⌘V 以純文字貼上。",
        "ko": "⇧⌘V로 기록을 엽니다. 항목을 두 번 클릭한 뒤 ⌘V — 또는 ⌃⌘V로 서식 없이 붙여넣습니다.",
    },
    "onboarding.browse.caption": {
        "zh-Hant": "按空白鍵可在時間軸上方預覽。點一下文字即可編輯。",
        "ko": "스페이스를 눌러 타임라인 위에서 미리봅니다. 텍스트를 클릭해 편집하세요.",
    },
    "onboarding.organize.caption": {
        "zh-Hant": "⌘-點選多個項目，再按 Return 依序貼上。",
        "ko": "⌘-클릭으로 여러 항목을 고른 뒤 Return으로 순서대로 붙여넣습니다.",
    },
    "onboarding.stack.caption": {
        "zh-Hant": "⇧⌘C 會在右側打開佇列。複製多項內容後，在目標 App 中按 ⌘V 逐一貼上。",
        "ko": "⇧⌘C로 오른쪽에 대기열을 엽니다. 여러 항목을 복사한 뒤 대상 App에서 ⌘V로 하나씩 붙여넣으세요.",
    },
    "onboarding.step.copy": {"zh-Hant": "複製", "ko": "복사"},
    "onboarding.step.saved": {"zh-Hant": "已保存", "ko": "저장됨"},
    "onboarding.step.open": {"zh-Hant": "打開", "ko": "열기"},
    "onboarding.step.doubleClick": {"zh-Hant": "按兩下", "ko": "두 번 클릭"},
    "onboarding.step.paste": {"zh-Hant": "貼上", "ko": "붙여넣기"},
    "onboarding.step.plain": {"zh-Hant": "純文字", "ko": "일반 텍스트"},
    "onboarding.step.space": {"zh-Hant": "空白鍵", "ko": "스페이스"},
    "onboarding.step.preview": {"zh-Hant": "預覽", "ko": "미리보기"},
    "onboarding.step.edit": {"zh-Hant": "編輯", "ko": "편집"},
    "onboarding.step.cmdClick": {"zh-Hant": "⌘-點選", "ko": "⌘-클릭"},
    "onboarding.step.order": {"zh-Hant": "順序", "ko": "순서"},
    "onboarding.step.return": {"zh-Hant": "Return", "ko": "Return"},
    "onboarding.demo.next": {"zh-Hant": "下一步", "ko": "다음"},
    "onboarding.demo.clickToEdit": {"zh-Hant": "點一下以編輯", "ko": "클릭하여 편집"},
    "onboarding.demo.copyToCollect": {"zh-Hant": "複製以收集", "ko": "복사하여 모으기"},
    "onboarding.demo.doubleClick": {"zh-Hant": "按兩下", "ko": "두 번 클릭"},
    "common.cancel": {"zh-Hant": "取消", "ko": "취소"},
    "common.delete": {"zh-Hant": "刪除", "ko": "삭제"},
    "common.create": {"zh-Hant": "建立", "ko": "만들기"},
}


def merge_batch_cjk(strings: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    merged = {key: dict(locs) for key, locs in strings.items()}
    missing = set(merged) - set(BATCH_CJK)
    if missing:
        raise SystemExit(f"Missing batch-CJK translations for: {sorted(missing)}")
    extra = set(BATCH_CJK) - set(merged)
    if extra:
        raise SystemExit(f"Unknown batch-CJK keys: {sorted(extra)}")
    for key, locs in BATCH_CJK.items():
        merged[key].update(locs)
    return merged
