"""French, German, Spanish, and Polish translations (batch 2)."""

from __future__ import annotations

BATCH2_LANGS = ("fr", "de", "es", "pl")

BATCH2: dict[str, dict[str, str]] = {
    "filter.all": {"fr": "Tous les types", "de": "Alle Typen", "es": "Todos los tipos", "pl": "Wszystkie typy"},
    "filter.text": {"fr": "Texte", "de": "Text", "es": "Texto", "pl": "Tekst"},
    "filter.number": {"fr": "Nombre", "de": "Zahl", "es": "Número", "pl": "Liczba"},
    "filter.link": {"fr": "Lien", "de": "Link", "es": "Enlace", "pl": "Link"},
    "filter.image": {"fr": "Image", "de": "Bild", "es": "Imagen", "pl": "Obraz"},
    "filter.file": {"fr": "Fichier", "de": "Datei", "es": "Archivo", "pl": "Plik"},
    "filter.byType": {"fr": "Filtrer par type", "de": "Nach Typ filtern", "es": "Filtrar por tipo", "pl": "Filtruj według typu"},
    "filter.clear": {"fr": "Effacer le filtre de type", "de": "Typfilter löschen", "es": "Borrar filtro de tipo", "pl": "Wyczyść filtr typu"},
    "tab.default": {"fr": "Par défaut", "de": "Standard", "es": "Predeterminado", "pl": "Domyślne"},
    "tab.pinned": {"fr": "Épinglés", "de": "Angeheftet", "es": "Fijados", "pl": "Przypięte"},
    "tab.folder": {"fr": "Dossier", "de": "Ordner", "es": "Carpeta", "pl": "Folder"},
    "clipType.text": {"fr": "Texte", "de": "Text", "es": "Texto", "pl": "Tekst"},
    "clipType.richText": {"fr": "Texte enrichi", "de": "Rich Text", "es": "Texto enriquecido", "pl": "Tekst sformatowany"},
    "clipType.html": {"fr": "HTML", "de": "HTML", "es": "HTML", "pl": "HTML"},
    "clipType.image": {"fr": "Image", "de": "Bild", "es": "Imagen", "pl": "Obraz"},
    "clipType.file": {"fr": "Fichier", "de": "Datei", "es": "Archivo", "pl": "Plik"},
    "clipType.url": {"fr": "Lien", "de": "Link", "es": "Enlace", "pl": "Link"},
    "clipType.mixed": {"fr": "Mixte", "de": "Gemischt", "es": "Mixto", "pl": "Mieszany"},
    "clipType.folder": {"fr": "Dossier", "de": "Ordner", "es": "Carpeta", "pl": "Folder"},
    "clipType.empty": {"fr": "Vide", "de": "Leer", "es": "Vacío", "pl": "Pusto"},
    "clipPreview.oneCharacter": {"fr": "1 caractère", "de": "1 Zeichen", "es": "1 carácter", "pl": "1 znak"},
    "clipPreview.characters": {"fr": "%lld caractères", "de": "%lld Zeichen", "es": "%lld caracteres", "pl": "%lld znaków"},
    "keepHistory.oneDay": {"fr": "1 jour", "de": "1 Tag", "es": "1 día", "pl": "1 dzień"},
    "keepHistory.oneWeek": {"fr": "1 semaine", "de": "1 Woche", "es": "1 semana", "pl": "1 tydzień"},
    "keepHistory.oneMonth": {"fr": "1 mois", "de": "1 Monat", "es": "1 mes", "pl": "1 miesiąc"},
    "keepHistory.forever": {"fr": "Pour toujours", "de": "Für immer", "es": "Para siempre", "pl": "Na zawsze"},
    "stack.fifo": {"fr": "Premier entré, premier sorti", "de": "Zuerst rein, zuerst raus", "es": "Primero en entrar, primero en salir", "pl": "Pierwsze weszło, pierwsze wyszło"},
    "stack.lifo": {"fr": "Dernier entré, premier sorti", "de": "Zuletzt rein, zuerst raus", "es": "Último en entrar, primero en salir", "pl": "Ostatnie weszło, pierwsze wyszło"},
    "stack.fifoHelp": {
        "fr": "Ordre de copie. Cliquez pour inverser.",
        "de": "Kopierreihenfolge. Klicken zum Umkehren.",
        "es": "Orden de copia. Haz clic para invertir.",
        "pl": "Kolejność kopiowania. Kliknij, aby odwrócić.",
    },
    "stack.lifoHelp": {
        "fr": "Le plus récent d'abord. Cliquez pour l'ordre de copie.",
        "de": "Neueste zuerst. Klicken für Kopierreihenfolge.",
        "es": "Lo más reciente primero. Haz clic para orden de copia.",
        "pl": "Najnowsze najpierw. Kliknij dla kolejności kopiowania.",
    },
    "stack.paste": {"fr": "Coller", "de": "Einfügen", "es": "Pegar", "pl": "Wklej"},
    "stack.open": {"fr": "Ouvrir la pile de collage", "de": "Einfügestapel öffnen", "es": "Abrir pila de pegado", "pl": "Otwórz stos wklejania"},
    "stack.close": {"fr": "Fermer la pile de collage", "de": "Einfügestapel schließen", "es": "Cerrar pila de pegado", "pl": "Zamknij stos wklejania"},
    "stack.title": {"fr": "Pile", "de": "Stapel", "es": "Pila", "pl": "Stos"},
    "stack.statusWithCount": {"fr": "Pile · %lld", "de": "Stapel · %lld", "es": "Pila · %lld", "pl": "Stos · %lld"},
    "stack.collecting": {"fr": "Collecte", "de": "Sammeln", "es": "Recopilando", "pl": "Zbieranie"},
    "stack.closeHelp": {"fr": "Fermer la pile de collage (⇧⌘C)", "de": "Einfügestapel schließen (⇧⌘C)", "es": "Cerrar pila de pegado (⇧⌘C)", "pl": "Zamknij stos wklejania (⇧⌘C)"},
    "stack.pasteNext": {"fr": "⌘V colle le suivant", "de": "⌘V fügt das Nächste ein", "es": "⌘V pega el siguiente", "pl": "⌘V wkleja następny"},
    "stack.emptyTitle": {"fr": "Copiez pour remplir la pile", "de": "Kopieren, um den Stapel zu füllen", "es": "Copia para llenar la pila", "pl": "Kopiuj, aby wypełnić stos"},
    "stack.emptySubtitle": {"fr": "Puis ⌘V dans n'importe quelle app", "de": "Dann ⌘V in einer beliebigen App", "es": "Luego ⌘V en cualquier app", "pl": "Potem ⌘V w dowolnej aplikacji"},
    "stack.accessibilityHint": {
        "fr": "Autorisez l'accessibilité pour que ⌘V fasse avancer la pile",
        "de": "Bedienungshilfen erlauben, damit ⌘V den Stapel voranbringt",
        "es": "Concede accesibilidad para que ⌘V avance la pila",
        "pl": "Zezwól na dostępność, aby ⌘V przechodziło do następnego",
    },
    "stack.resizeHelp": {"fr": "Glisser pour redimensionner la hauteur", "de": "Ziehen, um die Höhe zu ändern", "es": "Arrastra para cambiar la altura", "pl": "Przeciągnij, aby zmienić wysokość"},
    "stack.moveToNext": {"fr": "Passer au suivant", "de": "Zum Nächsten", "es": "Mover al siguiente", "pl": "Przenieś do następnego"},
    "stack.delete": {"fr": "Supprimer", "de": "Löschen", "es": "Eliminar", "pl": "Usuń"},
    "menu.openPaste": {"fr": "Ouvrir l'historique", "de": "Verlauf öffnen", "es": "Abrir historial", "pl": "Otwórz historię"},
    "menu.clearStack": {"fr": "Vider la pile de collage", "de": "Einfügestapel leeren", "es": "Vaciar pila de pegado", "pl": "Wyczyść stos wklejania"},
    "menu.pastePlain": {"fr": "Coller sans mise en forme", "de": "Als Text einfügen", "es": "Pegar sin formato", "pl": "Wklej bez formatowania"},
    "menu.pauseCapture": {"fr": "Suspendre la capture", "de": "Erfassung pausieren", "es": "Pausar captura", "pl": "Wstrzymaj przechwytywanie"},
    "menu.resumeCapture": {"fr": "Reprendre la capture", "de": "Erfassung fortsetzen", "es": "Reanudar captura", "pl": "Wznów przechwytywanie"},
    "menu.mcp": {"fr": "MCP", "de": "MCP", "es": "MCP", "pl": "MCP"},
    "menu.copyMcpURL": {"fr": "Copier l'URL MCP", "de": "MCP-URL kopieren", "es": "Copiar URL de MCP", "pl": "Kopiuj adres URL MCP"},
    "menu.preferences": {"fr": "Réglages…", "de": "Einstellungen…", "es": "Preferencias…", "pl": "Ustawienia…"},
    "menu.checkUpdates": {"fr": "Rechercher des mises à jour…", "de": "Nach Updates suchen…", "es": "Buscar actualizaciones…", "pl": "Sprawdź aktualizacje…"},
    "menu.quit": {"fr": "Quitter Paste It", "de": "Paste It beenden", "es": "Salir de Paste It", "pl": "Zakończ Paste It"},
    "menu.more": {"fr": "Plus", "de": "Mehr", "es": "Más", "pl": "Więcej"},
    "menu.statusTooltip": {
        "fr": "Paste It — maintenez ⌘C / ⌘V pour afficher les touches",
        "de": "Paste It — ⌘C / ⌘V gedrückt halten, um die Tasten anzuzeigen",
        "es": "Paste It — mantén ⌘C / ⌘V para ver las teclas",
        "pl": "Paste It — przytrzymaj ⌘C / ⌘V, aby pokazać klawisze",
    },
    "menu.statusClickHint": {
        "fr": "Clic gauche : historique · Clic droit : menu",
        "de": "Linksklick: Verlauf · Rechtsklick: Menü",
        "es": "Clic izquierdo: historial · Clic derecho: menú",
        "pl": "Lewy przycisk: historia · Prawy przycisk: menu",
    },
    "timeline.clearFilter": {"fr": "Effacer le filtre", "de": "Filter löschen", "es": "Borrar filtro", "pl": "Wyczyść filtr"},
    "timeline.selectedCount": {
        "fr": "%lld sélectionnés — Entrée pour coller",
        "de": "%lld ausgewählt — Eingabe zum Einfügen",
        "es": "%lld seleccionados — Intro para pegar",
        "pl": "Wybrano %lld — Return, aby wkleić",
    },
    "timeline.newFolder": {"fr": "Nouveau dossier", "de": "Neuer Ordner", "es": "Nueva carpeta", "pl": "Nowy folder"},
    "timeline.newFolderHelp": {"fr": "Nouveau dossier", "de": "Neuer Ordner", "es": "Nueva carpeta", "pl": "Nowy folder"},
    "timeline.search": {"fr": "Rechercher (⌘F)", "de": "Suchen (⌘F)", "es": "Buscar (⌘F)", "pl": "Szukaj (⌘F)"},
    "timeline.searchHistory": {"fr": "Rechercher dans l'historique", "de": "Verlauf durchsuchen", "es": "Buscar en el historial", "pl": "Przeszukaj historię"},
    "timeline.noMatch": {"fr": "Aucun élément correspondant", "de": "Keine passenden Einträge", "es": "No hay elementos coincidentes", "pl": "Brak pasujących elementów"},
    "timeline.noTypeInPinned": {
        "fr": "Aucun élément %@ dans Épinglés",
        "de": "Keine %@-Einträge in Angeheftet",
        "es": "No hay elementos %@ en Fijados",
        "pl": "Brak elementów %@ w Przypięte",
    },
    "timeline.noTypeInFolder": {
        "fr": "Aucun élément %@ dans ce dossier",
        "de": "Keine %@-Einträge in diesem Ordner",
        "es": "No hay elementos %@ en esta carpeta",
        "pl": "Brak elementów %@ w tym folderze",
    },
    "timeline.noType": {
        "fr": "Aucun élément %@",
        "de": "Keine %@-Einträge",
        "es": "No hay elementos %@",
        "pl": "Brak elementów %@",
    },
    "timeline.emptyDefault": {
        "fr": "Copiez quelque chose pour créer votre historique",
        "de": "Kopieren Sie etwas, um Ihren Verlauf aufzubauen",
        "es": "Copia algo para crear tu historial",
        "pl": "Skopiuj coś, aby zbudować historię schowka",
    },
    "timeline.emptyPinned": {
        "fr": "Épinglez des éléments pour les garder ici",
        "de": "Einträge anheften, um sie hier zu behalten",
        "es": "Fija elementos para conservarlos aquí",
        "pl": "Przypnij elementy, aby zachować je tutaj",
    },
    "timeline.emptyFolder": {
        "fr": "Ajoutez des éléments à ce dossier depuis le menu contextuel",
        "de": "Einträge über das Kontextmenü zu diesem Ordner hinzufügen",
        "es": "Añade elementos a esta carpeta desde el menú contextual",
        "pl": "Dodaj elementy do tego folderu z menu kontekstowego",
    },
    "timeline.unpin": {"fr": "Désépingler", "de": "Lösen", "es": "Desfijar", "pl": "Odepnij"},
    "timeline.pin": {"fr": "Épingler", "de": "Anheften", "es": "Fijar", "pl": "Przypnij"},
    "timeline.addToFolder": {"fr": "Ajouter au dossier", "de": "Zum Ordner hinzufügen", "es": "Añadir a carpeta", "pl": "Dodaj do folderu"},
    "timeline.removeFromFolder": {"fr": "Retirer du dossier", "de": "Aus Ordner entfernen", "es": "Quitar de carpeta", "pl": "Usuń z folderu"},
    "timeline.delete": {"fr": "Supprimer", "de": "Löschen", "es": "Eliminar", "pl": "Usuń"},
    "timeline.removeFromFolderAction": {"fr": "Retirer du dossier", "de": "Aus Ordner entfernen", "es": "Quitar de carpeta", "pl": "Usuń z folderu"},
    "timeline.copy": {"fr": "Copier dans le presse-papiers", "de": "In Zwischenablage kopieren", "es": "Copiar al portapapeles", "pl": "Kopiuj do schowka"},
    "timeline.copyPlain": {"fr": "Copier en texte brut", "de": "Als Klartext kopieren", "es": "Copiar como texto plano", "pl": "Kopiuj jako zwykły tekst"},
    "timeline.edit": {"fr": "Modifier", "de": "Bearbeiten", "es": "Editar", "pl": "Edytuj"},
    "timeline.cancel": {"fr": "Annuler", "de": "Abbrechen", "es": "Cancelar", "pl": "Anuluj"},
    "timeline.create": {"fr": "Créer", "de": "Erstellen", "es": "Crear", "pl": "Utwórz"},
    "settings.tab.about": {"fr": "À propos", "de": "Über", "es": "Acerca de", "pl": "Informacje"},
    "settings.tab.general": {"fr": "Général", "de": "Allgemein", "es": "General", "pl": "Ogólne"},
    "settings.tab.privacy": {"fr": "Confidentialité", "de": "Datenschutz", "es": "Privacidad", "pl": "Prywatność"},
    "settings.tab.folders": {"fr": "Dossiers", "de": "Ordner", "es": "Carpetas", "pl": "Foldery"},
    "settings.tab.stack": {"fr": "Pile", "de": "Stapel", "es": "Pila", "pl": "Stos"},
    "settings.tab.storage": {"fr": "Stockage", "de": "Speicher", "es": "Almacenamiento", "pl": "Pamięć"},
    "settings.version": {"fr": "Paste It %@ (%@)", "de": "Paste It %@ (%@)", "es": "Paste It %@ (%@)", "pl": "Paste It %@ (%@)"},
    "settings.aboutBlurb": {
        "fr": "Paste It est un gestionnaire de presse-papiers local. L'historique reste sur ce Mac.",
        "de": "Paste It ist ein lokaler Zwischenablage-Manager. Der Verlauf bleibt auf diesem Mac.",
        "es": "Paste It es un gestor de portapapeles local. El historial permanece en este Mac.",
        "pl": "Paste It to lokalny menedżer schowka. Historia pozostaje na tym Macu.",
    },
    "settings.versionLabel": {"fr": "Version", "de": "Version", "es": "Versión", "pl": "Wersja"},
    "settings.showTutorial": {"fr": "Afficher le tutoriel…", "de": "Tutorial anzeigen…", "es": "Mostrar tutorial…", "pl": "Pokaż samouczek…"},
    "settings.whatsNew": {"fr": "Nouveautés…", "de": "Neuigkeiten…", "es": "Novedades…", "pl": "Co nowego…"},
    "settings.checkingUpdates": {"fr": "Recherche de mises à jour…", "de": "Suche nach Updates…", "es": "Buscando actualizaciones…", "pl": "Sprawdzanie aktualizacji…"},
    "settings.pauseCapture": {"fr": "Suspendre la capture du presse-papiers", "de": "Zwischenablage-Erfassung pausieren", "es": "Pausar captura del portapapeles", "pl": "Wstrzymaj przechwytywanie schowka"},
    "settings.pastePlainDefault": {
        "fr": "Coller en texte brut par défaut",
        "de": "Standardmäßig als Klartext einfügen",
        "es": "Pegar como texto plano por defecto",
        "pl": "Domyślnie wklejaj jako zwykły tekst",
    },
    "settings.plainTextFootnote": {
        "fr": "⌃⌘V colle une fois en texte brut, puis restaure le presse-papiers d'origine (accessibilité requise pour le collage auto). Dans l'historique, ⇧↩ colle la sélection en texte brut.",
        "de": "⌃⌘V fügt einmal als Text ein und stellt die ursprüngliche Zwischenablage wieder her (Bedienungshilfen für Auto-Einfügen). Im Verlauf fügt ⇧↩ die Auswahl als Text ein.",
        "es": "⌃⌘V pega una vez como texto plano y restaura el portapapeles original (se requiere accesibilidad para pegado automático). En el historial, ⇧↩ pega la selección como texto plano.",
        "pl": "⌃⌘V wkleja raz jako zwykły tekst, potem przywraca oryginalny schowek (wymagana dostępność do auto-wklejania). W historii ⇧↩ wkleja zaznaczenie jako zwykły tekst.",
    },
    "settings.launchAtLogin": {"fr": "Ouvrir à la connexion", "de": "Beim Anmelden öffnen", "es": "Abrir al iniciar sesión", "pl": "Uruchamiaj przy logowaniu"},
    "settings.keepHistory": {"fr": "Conserver l'historique", "de": "Verlauf behalten", "es": "Conservar historial", "pl": "Zachowaj historię"},
    "settings.maxHistoryItems": {"fr": "Nombre max. d'éléments", "de": "Max. Verlaufseinträge", "es": "Máx. elementos del historial", "pl": "Maks. liczba elementów historii"},
    "settings.clipboardPolling": {"fr": "Interrogation du presse-papiers", "de": "Zwischenablage-Abfrage", "es": "Sondeo del portapapeles", "pl": "Odpytywanie schowka"},
    "settings.seconds": {"fr": "s", "de": "s", "es": "s", "pl": "s"},
    "settings.stackDirection": {"fr": "Direction de collage par défaut", "de": "Standard-Einfügerichtung", "es": "Dirección de pegado predeterminada", "pl": "Domyślny kierunek wklejania"},
    "settings.stackFootnote": {
        "fr": "⇧⌘C ouvre ou ferme la pile de collage. Tant qu'elle contient des éléments, ⌘V dans une app colle le suivant (accessibilité requise). Les contrôles sont dans le panneau Pile et le menu ⋯.",
        "de": "⇧⌘C öffnet oder schließt den Einfügestapel. Solange Einträge vorhanden sind, fügt ⌘V in einer App den nächsten ein (Bedienungshilfen erforderlich). Steuerung im Stapel-Panel und im ⋯-Menü.",
        "es": "⇧⌘C abre o cierra la pila de pegado. Mientras tenga elementos, ⌘V en cualquier app pega el siguiente (se requiere accesibilidad). Los controles están en el panel Pila y el menú ⋯.",
        "pl": "⇧⌘C otwiera lub zamyka stos wklejania. Gdy ma elementy, ⌘V w dowolnej aplikacji wkleja następny (wymagana dostępność). Sterowanie w panelu Stos i menu ⋯.",
    },
    "settings.maxBinaryStorage": {
        "fr": "Stockage binaire max. : %lld Mo",
        "de": "Max. Binärspeicher: %lld MB",
        "es": "Almacenamiento binario máx.: %lld MB",
        "pl": "Maks. pamięć binarna: %lld MB",
    },
    "settings.pruneNow": {"fr": "Nettoyer maintenant", "de": "Jetzt bereinigen", "es": "Limpiar ahora", "pl": "Oczyść teraz"},
    "settings.clearKeepPinned": {
        "fr": "Effacer l'historique, garder les épinglés",
        "de": "Verlauf löschen, Angeheftetes behalten",
        "es": "Borrar historial, conservar fijados",
        "pl": "Wyczyść historię, zachowaj przypięte",
    },
    "settings.clearAllHistory": {"fr": "Tout effacer", "de": "Gesamten Verlauf löschen", "es": "Borrar todo el historial", "pl": "Wyczyść całą historię"},
    "folders.pinnedFooter": {
        "fr": "L'onglet Épinglés ne peut pas être renommé ni supprimé. Utilisez Épingler / Désépingler sur les éléments.",
        "de": "Der Tab Angeheftet kann nicht umbenannt oder gelöscht werden. Anheften/Lösen über die Einträge.",
        "es": "La pestaña Fijados no se puede renombrar ni eliminar. Usa Fijar / Desfijar en los elementos.",
        "pl": "Karty Przypięte nie można zmienić nazwy ani usunąć. Użyj Przypnij / Odepnij na elementach.",
    },
    "folders.noCustom": {"fr": "Aucun dossier personnalisé", "de": "Keine benutzerdefinierten Ordner", "es": "No hay carpetas personalizadas", "pl": "Brak własnych folderów"},
    "folders.rename": {"fr": "Renommer…", "de": "Umbenennen…", "es": "Renombrar…", "pl": "Zmień nazwę…"},
    "folders.addHelp": {"fr": "Ajouter un dossier", "de": "Ordner hinzufügen", "es": "Añadir carpeta", "pl": "Dodaj folder"},
    "folders.renameHelp": {"fr": "Renommer le dossier", "de": "Ordner umbenennen", "es": "Renombrar carpeta", "pl": "Zmień nazwę folderu"},
    "folders.deleteHelp": {"fr": "Supprimer le dossier", "de": "Ordner löschen", "es": "Eliminar carpeta", "pl": "Usuń folder"},
    "folders.footer": {
        "fr": "Créez jusqu'à %lld dossiers personnalisés. Ils apparaissent à côté de Par défaut et Épinglés. Les éléments des dossiers sont conservés lors du nettoyage.",
        "de": "Bis zu %lld benutzerdefinierte Ordner. Sie erscheinen neben Standard und Angeheftet. Ordner-Einträge bleiben bei der Bereinigung erhalten.",
        "es": "Crea hasta %lld carpetas personalizadas. Aparecen junto a Predeterminado y Fijados. Los elementos en carpetas se conservan al limpiar.",
        "pl": "Utwórz do %lld własnych folderów. Pojawią się obok Domyślne i Przypięte. Elementy w folderach są zachowywane przy czyszczeniu.",
    },
    "folders.renameTitle": {"fr": "Renommer le dossier", "de": "Ordner umbenennen", "es": "Renombrar carpeta", "pl": "Zmień nazwę folderu"},
    "folders.namePlaceholder": {"fr": "Nom du dossier", "de": "Ordnername", "es": "Nombre de carpeta", "pl": "Nazwa folderu"},
    "folders.renameConfirm": {"fr": "Renommer", "de": "Umbenennen", "es": "Renombrar", "pl": "Zmień nazwę"},
    "privacy.analytics": {"fr": "Analytique", "de": "Analyse", "es": "Analítica", "pl": "Analityka"},
    "privacy.shareAnalytics": {
        "fr": "Partager des statistiques d'utilisation anonymes",
        "de": "Anonyme Nutzungsstatistiken teilen",
        "es": "Compartir analítica de uso anónima",
        "pl": "Udostępniaj anonimową analitykę użycia",
    },
    "privacy.whatWeCollect": {"fr": "Ce que nous collectons", "de": "Was wir erfassen", "es": "Qué recopilamos", "pl": "Co zbieramy"},
    "privacy.eventsBlurb": {
        "fr": "Les événements aident à améliorer Paste It (activation, panneau, mises à jour). Les données sont anonymes et envoyées à PostHog si activé.",
        "de": "Ereignisse helfen, Paste It zu verbessern (Aktivierung, Panel, Updates). Daten sind anonym und werden bei Aktivierung an PostHog gesendet.",
        "es": "Los eventos ayudan a mejorar Paste It (activación, panel, actualizaciones). Los datos son anónimos y se envían a PostHog si está activado.",
        "pl": "Zdarzenia pomagają ulepszać Paste It (aktywacja, panel, aktualizacje). Dane są anonimowe i wysyłane do PostHog po włączeniu.",
    },
    "privacy.neverCollected": {"fr": "Jamais collecté", "de": "Nie erfasst", "es": "Nunca recopilado", "pl": "Nigdy nie zbierane"},
    "privacy.productEvents": {"fr": "Événements produit", "de": "Produkt-Ereignisse", "es": "Eventos del producto", "pl": "Zdarzenia produktu"},
    "privacy.fullDisclosure": {"fr": "Divulgation complète sur GitHub", "de": "Vollständige Offenlegung auf GitHub", "es": "Divulgación completa en GitHub", "pl": "Pełne ujawnienie na GitHub"},
    "privacy.analyticsFooter": {
        "fr": "Facultatif. Désactivé = aucun événement envoyé. Voir %@ dans le dépôt open source.",
        "de": "Optional. Aus = keine Ereignisse. Siehe %@ im Open-Source-Repo.",
        "es": "Opcional. Desactivado = no se envían eventos. Consulta %@ en el repositorio abierto.",
        "pl": "Opcjonalne. Wyłączone = brak zdarzeń. Zobacz %@ w repozytorium open source.",
    },
    "privacy.noIgnoredApps": {"fr": "Aucune app ignorée", "de": "Keine ignorierten Apps", "es": "No hay apps ignoradas", "pl": "Brak ignorowanych aplikacji"},
    "privacy.addApp": {"fr": "Ajouter une app", "de": "App hinzufügen", "es": "Añadir app", "pl": "Dodaj aplikację"},
    "privacy.removeApp": {"fr": "Retirer l'app", "de": "App entfernen", "es": "Quitar app", "pl": "Usuń aplikację"},
    "privacy.ignoredApps": {"fr": "Apps ignorées", "de": "Ignorierte Apps", "es": "Apps ignoradas", "pl": "Ignorowane aplikacje"},
    "privacy.ignoredAppsFooter": {
        "fr": "Les copies dans ces apps ne sont jamais enregistrées. Utile pour les gestionnaires de mots de passe et apps sensibles.",
        "de": "Kopien in diesen Apps werden nie gespeichert. Für Passwort-Manager und sensible Apps.",
        "es": "Las copias en estas apps nunca se guardan. Útil para gestores de contraseñas y apps sensibles.",
        "pl": "Kopie w tych aplikacjach nie są zapisywane. Dla menedżerów haseł i wrażliwych aplikacji.",
    },
    "privacy.protectedContent": {"fr": "Contenu protégé", "de": "Geschützter Inhalt", "es": "Contenido protegido", "pl": "Chroniona zawartość"},
    "privacy.protectedBlurb": {
        "fr": "Les marqueurs sensibles du presse-papiers — champs de mot de passe, clips temporaires — sont ignorés automatiquement.",
        "de": "Sensible Zwischenablage-Markierungen — Passwortfelder, temporäre Clips — werden automatisch ignoriert.",
        "es": "Los marcadores sensibles del portapapeles — campos de contraseña, clips temporales — se ignoran automáticamente.",
        "pl": "Wrażliwe znaczniki schowka — pola haseł, tymczasowe klipy — są automatycznie ignorowane.",
    },
    "privacy.protectedFooter": {
        "fr": "Apps ignorées excluent toute une app. Contenu protégé exclut uniquement les données sensibles marquées, de toute app.",
        "de": "Ignorierte Apps überspringen alles von einer App. Geschützter Inhalt nur markierte sensible Daten, von jeder App.",
        "es": "Apps ignoradas omiten todo de una app. Contenido protegido solo omite datos sensibles marcados, de cualquier app.",
        "pl": "Ignorowane aplikacje pomijają całą aplikację. Chroniona zawartość pomija tylko oznaczone dane wrażliwe z dowolnej aplikacji.",
    },
    "privacy.addIgnoredApp": {"fr": "Ajouter une app ignorée", "de": "Ignorierte App hinzufügen", "es": "Añadir app ignorada", "pl": "Dodaj ignorowaną aplikację"},
    "privacy.chooseApp": {"fr": "Choisir…", "de": "Auswählen…", "es": "Elegir…", "pl": "Wybierz…"},
    "privacy.search": {"fr": "Rechercher", "de": "Suchen", "es": "Buscar", "pl": "Szukaj"},
    "privacy.loadingApps": {"fr": "Chargement des apps…", "de": "Apps werden geladen…", "es": "Cargando apps…", "pl": "Ładowanie aplikacji…"},
    "privacy.chooseAppPanel": {"fr": "Choisir une app à ignorer", "de": "App zum Ignorieren auswählen", "es": "Elegir una app para ignorar", "pl": "Wybierz aplikację do ignorowania"},
    "onboarding.capture.title": {"fr": "Copier pour enregistrer", "de": "Kopieren zum Speichern", "es": "Copiar para guardar", "pl": "Kopiuj, aby zapisać"},
    "onboarding.paste.title": {"fr": "Choisir dans l'historique", "de": "Aus dem Verlauf wählen", "es": "Elegir del historial", "pl": "Wybierz z historii"},
    "onboarding.browse.title": {"fr": "Aperçu et modification", "de": "Vorschau und Bearbeitung", "es": "Vista previa y edición", "pl": "Podgląd i edycja"},
    "onboarding.organize.title": {"fr": "Collage multiple", "de": "Mehrfach-Einfügen", "es": "Pegado múltiple", "pl": "Wklejanie wielokrotne"},
    "onboarding.stack.title": {"fr": "Pile de collage", "de": "Einfügestapel", "es": "Pila de pegado", "pl": "Stos wklejania"},
    "onboarding.capture.caption": {
        "fr": "Copiez n'importe quoi — Paste It l'enregistre et affiche ⌘C dans la barre de menus.",
        "de": "Alles kopieren — Paste It speichert es und blinkt ⌘C in der Menüleiste.",
        "es": "Copia cualquier cosa — Paste It la guarda y muestra ⌘C en la barra de menús.",
        "pl": "Kopiuj cokolwiek — Paste It zapisuje i miga ⌘C na pasku menu.",
    },
    "onboarding.paste.caption": {
        "fr": "⇧⌘V ouvre l'historique. Double-cliquez un élément, puis ⌘V — ou ⌃⌘V sans mise en forme.",
        "de": "⇧⌘V öffnet den Verlauf. Doppelklick auf Eintrag, dann ⌘V — oder ⌃⌘V ohne Formatierung.",
        "es": "⇧⌘V abre el historial. Doble clic en un elemento, luego ⌘V — o ⌃⌘V sin formato.",
        "pl": "⇧⌘V otwiera historię. Kliknij dwukrotnie element, potem ⌘V — lub ⌃⌘V bez formatowania.",
    },
    "onboarding.browse.caption": {
        "fr": "Appuyez sur Espace pour prévisualiser au-dessus de l'historique. Cliquez le texte pour modifier.",
        "de": "Leertaste für die Vorschau über dem Verlauf. Text anklicken zum Bearbeiten.",
        "es": "Pulsa Espacio para previsualizar sobre el historial. Haz clic en el texto para editar.",
        "pl": "Naciśnij Spację, aby podejrzeć nad historią. Kliknij tekst, aby edytować.",
    },
    "onboarding.organize.caption": {
        "fr": "⌘-cliquez plusieurs éléments, puis Entrée pour les coller dans l'ordre.",
        "de": "⌘-Klick auf mehrere Einträge, dann Eingabe zum Einfügen in Reihenfolge.",
        "es": "⌘-clic en varios elementos, luego Intro para pegarlos en orden.",
        "pl": "⌘-kliknij kilka elementów, potem Return, aby wkleić w kolejności.",
    },
    "onboarding.stack.caption": {
        "fr": "⇧⌘C ouvre une file à droite. Copiez plusieurs éléments, puis ⌘V dans l'app cible un par un.",
        "de": "⇧⌘C öffnet eine Warteschlange rechts. Mehrere Dinge kopieren, dann ⌘V in der Ziel-App nacheinander.",
        "es": "⇧⌘C abre una cola a la derecha. Copia varias cosas, luego ⌘V en la app destino una a una.",
        "pl": "⇧⌘C otwiera kolejkę po prawej. Skopiuj kilka rzeczy, potem ⌘V w docelowej aplikacji po kolei.",
    },
    "onboarding.step.copy": {"fr": "Copier", "de": "Kopieren", "es": "Copiar", "pl": "Kopiuj"},
    "onboarding.step.saved": {"fr": "Enregistré", "de": "Gespeichert", "es": "Guardado", "pl": "Zapisano"},
    "onboarding.step.open": {"fr": "Ouvrir", "de": "Öffnen", "es": "Abrir", "pl": "Otwórz"},
    "onboarding.step.doubleClick": {"fr": "Double-clic", "de": "Doppelklick", "es": "Doble clic", "pl": "Dwuklik"},
    "onboarding.step.paste": {"fr": "Coller", "de": "Einfügen", "es": "Pegar", "pl": "Wklej"},
    "onboarding.step.plain": {"fr": "Brut", "de": "Klartext", "es": "Plano", "pl": "Zwykły"},
    "onboarding.step.space": {"fr": "Espace", "de": "Leertaste", "es": "Espacio", "pl": "Spacja"},
    "onboarding.step.preview": {"fr": "Aperçu", "de": "Vorschau", "es": "Vista previa", "pl": "Podgląd"},
    "onboarding.step.edit": {"fr": "Modifier", "de": "Bearbeiten", "es": "Editar", "pl": "Edytuj"},
    "onboarding.step.cmdClick": {"fr": "⌘-clic", "de": "⌘-Klick", "es": "⌘-clic", "pl": "⌘-klik"},
    "onboarding.step.order": {"fr": "Ordre", "de": "Reihenfolge", "es": "Orden", "pl": "Kolejność"},
    "onboarding.step.return": {"fr": "Entrée", "de": "Eingabe", "es": "Intro", "pl": "Return"},
    "onboarding.demo.next": {"fr": "SUIVANT", "de": "WEITER", "es": "SIGUIENTE", "pl": "DALEJ"},
    "onboarding.demo.clickToEdit": {"fr": "Cliquer pour modifier", "de": "Klicken zum Bearbeiten", "es": "Haz clic para editar", "pl": "Kliknij, aby edytować"},
    "onboarding.demo.copyToCollect": {"fr": "Copier pour collecter", "de": "Kopieren zum Sammeln", "es": "Copiar para recopilar", "pl": "Kopiuj, aby zebrać"},
    "onboarding.demo.doubleClick": {"fr": "Double-clic", "de": "Doppelklick", "es": "Doble clic", "pl": "Dwuklik"},
    "common.cancel": {"fr": "Annuler", "de": "Abbrechen", "es": "Cancelar", "pl": "Anuluj"},
    "common.delete": {"fr": "Supprimer", "de": "Löschen", "es": "Eliminar", "pl": "Usuń"},
    "common.create": {"fr": "Créer", "de": "Erstellen", "es": "Crear", "pl": "Utwórz"},
}


def merge_batch2(strings: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    merged = {key: dict(locs) for key, locs in strings.items()}
    missing = set(merged) - set(BATCH2)
    if missing:
        raise SystemExit(f"Missing batch-2 translations for: {sorted(missing)}")
    extra = set(BATCH2) - set(merged)
    if extra:
        raise SystemExit(f"Unknown batch-2 keys: {sorted(extra)}")
    for key, locs in BATCH2.items():
        merged[key].update(locs)
    return merged
